#pragma once

#define BUTTON_STATUS_INACTIVE	0x00
#define BUTTON_STATUS_ACTIVE	0x01
#define BUTTON_STATUS_SELECT	0x02

#define BUTTON_STATUS_CUSTOM_0	0x04
#define BUTTON_STATUS_CUSTOM_1	0x08
#define BUTTON_STATUS_CUSTOM_2	0x10
#define BUTTON_STATUS_CUSTOM_3	0x20
#define BUTTON_STATUS_CUSTOM_4	0x40
#define BUTTON_STATUS_CUSTOM_5	0x80

#define BUTTON_STATUSE_ALL		0xFF