#pragma once

#define OPEN_GL_REALISATION_FULL	0xFF
#define OPEN_GL_REALISATION_NOTHING	0x00

#define OPEN_GL_REALISATION_SELECT	0x01
#define OPEN_GL_REALISATION_BACK	0x02


#define OPEN_GL_REALISATION_BUTTON_LOST 2

#define OPEN_GL_REALISATION_FRAMES_AFTER_CALLBAC_COUNT	3