#pragma once

//#include "../Classes/GameEngine.h"

#define OPEN_GL_REALISATION_FULL	0xFF
#define OPEN_GL_REALISATION_NOTHING	0x00

#define OPEN_GL_REALISATION_SELECT	0x01
#define OPEN_GL_REALISATION_BACK	0x02


#define OPEN_GL_REALISATION_BUTTON_LOST 2

#define OPEN_GL_REALISATION_FRAMES_AFTER_CALLBAC_COUNT	3

#define SHIP_0_ROTATE_BUTTON	GLFW_KEY_Q
#define SHIP_0_SHOOT_BUTTON		GLFW_KEY_A
#define SHIP_1_ROTATE_BUTTON	GLFW_KEY_PAGE_DOWN
#define SHIP_1_SHOOT_BUTTON		GLFW_KEY_PAGE_UP
#define SHIP_2_ROTATE_BUTTON	GLFW_KEY_LEFT
#define SHIP_2_SHOOT_BUTTON		GLFW_KEY_DOWN
#define SHIP_3_ROTATE_BUTTON	GLFW_KEY_C
#define SHIP_3_SHOOT_BUTTON		GLFW_KEY_V

